### ISSUE TITLE
C++ port

### ISSUE THREAD

**Issue by JanDeVisser** [jazzycamel/QLed#3]
Hi-

I just ported your QLed to C++. Do you care having it in your repo here? Or should create my own? Either way is fine with me.

**Comment by jazzycamel** [comment]
Hi Jan,

Your work, your repo :) 
Let me know the URL and I will provide a link in the README from here so anyone who ends up here wanting a C++ implementation can find your project.

Thanks for asking and I hope this module has been some use to you.

Kr, Rob
